backend:
  name: github
  repo: zharkovstas/pishi-vlastyam
  site_domain: cms.netlify.com
media_folder: "src/static/img/uploads"
public_folder: "/img/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Authorities"
        name: "authorities"
        file: "src/authorities.yml"
        fields:
          - label: Authorities
            name: authorities
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Feedback Url, name: feedbackUrl, widget: string}
              - {label: Tags, name: tags, widget: list}
